jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run: npm install -q
      - snyk/scan
      - run: npm test
orbs:
  snyk: snyk/snyk@x.y.z
version: 2.1
