jobs:
  build:
    docker:
      - image: "circleci/node:latest"
    steps:
      - checkout
      - run: cd frontend
      - run: npm install -q
      - snyk/scan
orbs:
  snyk: snyk/snyk@x.y.z
version: 2.1
